# Generated by Django 4.1.2 on 2022-10-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="static/product/thumbnail_img"
                    ),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True, upload_to="static/product/detail_img"
                    ),
                ),
                ("description", models.TextField()),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_detail", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("amount", models.IntegerField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
