# Generated by Django 4.1.2 on 2022-10-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="상품에 대한 설명을 입력하세요."),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_public",
            field=models.BooleanField(default=False, help_text="공개 설정"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="상품명을 입력해주세요.", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, help_text="썸네일을 ", upload_to="static/product/thumbnail_img"
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="amount",
            field=models.IntegerField(blank=True, help_text="재고량을 입력하세요."),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="option_detail",
            field=models.CharField(
                help_text="상품에 대한 수량 혹은 무게에 대한 설명을 입력하세요.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="price",
            field=models.IntegerField(help_text="가격을 입력하세요."),
        ),
    ]
