# Generated by Django 4.1.2 on 2022-10-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="cart_id",
            new_name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
